apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-marketplace-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-marketplace-java
  template:
    metadata:
      labels:
        app: api-marketplace-java
    spec:
      containers:
        - name: api-marketplace-java
          image: n4kgod/api-boaventuramarketplace-java-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/usersdb?createDatabaseIfNotExists=true
            - name: SPRING_DATASOURCE_USERNAME
              value: user
            - name: SPRING_DATASOURCE_PASSWORD
              value: userpassword
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api-marketplace-java
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort