version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-marketplace
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: usersdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-marketplace-java
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-marketplace:3306/usersdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: userpassword
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: nginx-marketplace
    ports:
      - "3030:3030"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  mysql-data: